### ISSUE TITLE
No script asset for TagsConfig.

### ISSUE THREAD

**Issue by Ponyu-dev** [StarKRE22/Atomic#14]
Версия Framework: 1.0.1
Версия Unity: 2021.3.7f

Невозможно добавлять новые тэги.

### Ошибка
`No script asset for TagsConfig. Check that the definition is in a file of the same name and that it compiles properly.`

### Скрин ошибки: Видно то что скрипт не подтянулся.
<img width="488" alt="Screenshot 2024-11-06 at 13 10 46" src="https://github.com/user-attachments/assets/0c01399f-6477-4dd1-819f-4d9f557df430">

### Как исправил я.
Файл TagConfig.cs лежащий по пути Assets/Plugins/Atomic/Entities/Editor/Console/Tag/TagConfig.cs
Но сам класс называется Tag`s`Config

Я просто переименовал класс Tag`s`Config на TagConfig.

И все заработало.

**Comment by StarKRE22** [comment]
Спасибо большое за комментарий, в новой версии не будет таких конфигов!
