### ISSUE TITLE
По какой причине отсутствует библиотека Atomic с реактивными типами данных в sample проекте и в самом фреймворке? 

### ISSUE THREAD

**Issue by Lyten02** [StarKRE22/Atomic#21]
Я смотрел на стриме тип данных Atomic он был очень удобный. Хотелось бы понять почему его нет. Сейчас есть только IReactive, из-за отсутствия примеров в sample проекте в котором используется R3 сложно понять как правильно связывать и какие уровни абстракций было бы лучше использовать в определенные моменты.

**Comment by Lyten02** [comment]
Хочу добавить что я везде Expression писал с bool в <>

**Comment by Lyten02** [comment]
<bool>

**Comment by StarKRE22** [comment]
IReactive — это и есть Atomic, в Sample проекте не используется R3, а используется Atomic.Elements, в котором свои реактивные свойства и коллекции
