### ISSUE TITLE
Есть ли рекомендуемая версия Unity под данный фрейм ворк?

### ISSUE THREAD

**Issue by Lyten02** [StarKRE22/Atomic#23]
На стриме помню упоминалось что баги с ссылками должны пофиксится в 6000 версии.

**Comment by StarKRE22** [comment]
Сам работаю на 2022.3.42f

**Comment by Lyten02** [comment]
Я работаю сейчас на 6000 там нет багов тестировал еще на 2023 баги с ссылками даже перемещение в списках не корректно работает думаю следует указать рекомендованные версии
