### ISSUE TITLE
Не работает инсталеры без EntityController.

### ISSUE THREAD

**Issue by Lyten02** [StarKRE22/Atomic#4]
Ивенты в инсталерах не работают без компонента EntityController, а он по дефолту не добавляется почему так? На картинке показано как не будет работать 
![image](https://github.com/user-attachments/assets/ef92e4b3-5a39-4d7e-810a-3da632e80020)

**Comment by StarKRE22** [comment]
Смотри, Untiy ивенты не работают без EntityController, и это сделано специально, чтобы твоя игровая сущность не зависела от жизненного цикла MonoBehaviour. Такое разделение позволяет самостоятельно вызывать апдейты и активацию игровых объектов, если нужно делать это кастомно

Например, у Photon Fusion свой апдейт, который не привязан к Unity, поэтому у разработчику нужно сделать свой
NetworkEntityController, который будет управлять SceneEntity. 

Также, если тебе нужен мир со всеми сущностями, есть такой компонент EntityWorld, который будет хранить их всех. И можно вызывать один апдейт для всех сущностей в мире через EntiyWorldController. Таким образом, EntityController не нужно вешать на каждый GameObject.

Надеюсь получилось объяснить. Ключевая цель — оставить за разработчиком контроль над жизненным циклом сущностей и кастомизировать его вызовы под свой проект

**Comment by StarKRE22** [comment]
А EntiyInstaller работает, так как в компоненте Entity стоит галочка InstallOnAwake
