### ISSUE TITLE
Баги в консоли

### ISSUE THREAD

**Issue by Talmagett** [StarKRE22/Atomic#5]
В консоли Entity/Context, когда у нас есть несколько категорий. Если мы сделаем фокус на инпут поле, и будем менять его значение, но не нажав [+] сменить категорию, то мы будем редактировать поле другой категории. В некоторых моментах это может немного сломать API. )

**Comment by StarKRE22** [comment]
@Talmagett Спасибо большое! Постараюсь скоро поправить и выкатить апдейт!
