### ISSUE TITLE
Сделать категории для отладки в дебаге!

### ISSUE THREAD

**Issue by StarKRE22** [StarKRE22/Atomic#6]
А, я не так понял.  Я имел ввиду в плей моде. Для отладки удобно лазить смотреть данные в энтити. Но когда их там 3 страницы, то уже не очень удобно без категорий каких-то.

**Comment by ArnCarveris** [comment]
ref: https://github.com/JohnBaracuda/com.baracuda.runtime-monitoring

**Comment by StarKRE22** [comment]
Сделал поиск и сортировку айдишников по имени
