### ISSUE TITLE
Reload Domain and Scene. Atomic Event

### ISSUE THREAD

**Issue by Talmagett** [StarKRE22/Atomic#7]
Привет! Из-за того что у меня слабый ноут, включаю ProjectSettings -> Editor -> Do not reload Domain and Scene.

Если запускаю PlayMode не с первого раза, то Behaviour добавляются дважды, если у Entity уже есть в Debugе Behaviour. Или как-то ограничить дупликацию Behavioura.

Также у вас раньше был AtomicEvent, но почему-то он стал Event - который конфликтует с Unity Event, что бывает проблематично добавление через консоль.

**Comment by StarKRE22** [comment]
"Также у вас раньше был AtomicEvent, но почему-то он стал Event - который конфликтует с Unity Event, что бывает проблематично добавление через консоль." — вот это поправил

**Comment by StarKRE22** [comment]
Поправил
